### ISSUE TITLE
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by RandeeCao** [chunquedong/axbasePlugin#2]
运行环境:android4.3   x86机型   asus zenfone6

05-31 11:51:03.417: E/AndroidRuntime(20369): java.lang.NoClassDefFoundError: info/axbase/appex/MainActivity$1
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at info.axbase.appex.MainActivity.<init>(MainActivity.java:18)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at java.lang.Class.newInstanceImpl(Native Method)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at java.lang.Class.newInstance(Class.java:1208)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at info.axbase.plugin.AxInstrumentation.newActivity(AxInstrumentation.java:56)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2216)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at android.os.Looper.loop(Looper.java:149)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at android.app.ActivityThread.main(ActivityThread.java:5257)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at dalvik.system.NativeStart.main(Native Method)
05-31 11:51:03.417: E/AndroidRuntime(20369): Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at dalvik.system.DexFile.defineClassNative(Native Method)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at dalvik.system.DexFile.defineClass(DexFile.java:222)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at dalvik.system.DexPathList.findClass(DexPathList.java:322)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
05-31 11:51:03.417: E/AndroidRuntime(20369): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)

**Comment by chunquedong** [comment]
导致这个bug的最可能的原因是类被打上CLASS_ISPREVERIFIED标记。[详见这里](http://my.oschina.net/bugly/blog/536077?p={{currentPage-1}})
最简单的解决办法是插件打包时排除宿主中已经有的类。

谢谢反馈，有空的时候我会修复这个。你是直接使用demo没有做其他修改吗？你确定这个bug与机型有关系吗？

**Comment by RandeeCao** [comment]
恩 我直接运行mainActivity
我这边测试了3台设备
三星S4 4.4.2     崩溃
nexus 6  6.0     正常
asus zonfone6  4.3 崩溃

**Comment by chunquedong** [comment]
基本修复，wiki里面加了说明
